### PR TITLE
Fix multiple definitions of non-static functions

### PR DESCRIPTION
**Pull request by diwo**

### CODE REVIEW

**Comment by WerWolv** [comment]
Uhh is that really the only way to do it? Having a unused template argument there feels really strange

**Comment by diwo** [comment]
Well it's either this or split the definition down to TESLA_INIT_IMPL

**Comment by WerWolv** [comment]
I think moving it down would be the cleaner way. It feels very hacky otherwise

**Comment by WerWolv** [comment]
Wait. Why not just make the functions static? That would fix it too and would be even cleaner

**Comment by diwo** [comment]
Yeah that's what I'm about to try out

**Comment by diwo** [comment]
Static isn't much prettier either, it requires forward declaration up top next to declaration for `loop` because it's a friend of overlay. It's also not a template so it's has warnings for being unused.
```
[[maybe_unused]] static void goBack();
```

**Pull request merged**
