### PR TITLE
Provide filename as first argument

### PR DESCRIPTION
**Pull request by masagrator**
This allow us to retrieve filename if user decides to change it for whatever reason.

I am reloading overlay in Status Monitor when trying to use Micro mode, but many people would like to change its name and I am currently blocking access to Micro mode if filename was changed. This would allow to seamless interaction with different filenames.

This also matches how terminals like bash or cmd interact with external apps.

### CODE REVIEW

**Comment by WerWolv** [comment]
Thank you!

**Comment by masagrator** [comment]
Can I ask when can we expect next release of Tesla Menu? Since for this to be widely used first Tesla Menu must be released. :P

**Comment by WerWolv** [comment]
If you can recompile the Tesla Menu for me using this libtesla version real quick, I can make a release today

**Comment by masagrator** [comment]
[ovlmenu.zip](https://github.com/WerWolv/libtesla/files/11581942/ovlmenu.zip)
This is with updated makefile to version 1.2.3 :P

**Comment by WerWolv** [comment]
Here you go https://github.com/WerWolv/Tesla-Menu/releases/tag/v1.2.3

**Comment by masagrator** [comment]
Thanks. :)

**Pull request merged**
